version: "3.9"

services:
  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "3601:3601"
    environment:
      - PORT=3601
      - GENERATE_SOURCEMAP=true
    env_file:
      - .env.development.local