version: "3.9"

services:
  api:
    extends:
      file: ./api/docker-services.dev.yml
      service: api
    networks:
      - private
      - public
#  frontend:
#    extends:
#      file: ./frontend/docker-services.dev.yml
#      service: frontend
#    networks:
#      - public
#    depends_on:
#      - api
networks:
  public:
  private: