version: "3.9"

services:
  post-battle-api:
    extends:
      file: ./api/docker-services.yml
      service: post-battle-api
    networks:
      - private
      - public
      - nginx_bridge
  post-battle-frontend:
    extends:
      file: ./frontend/docker-services.yml
      service: post-battle-frontend
    networks:
      - public
      - nginx_bridge
    depends_on:
      - post-battle-api
networks:
  public:
  private:
  nginx_bridge:
    external: true
    name: nginx_bridge