version: "3.9"

services:
  post-battle-api:
    extends:
      file: ./api/docker-services.dev.yml
      service: post-battle-api
    networks:
      - private
      - public
  post-battle-frontend:
    extends:
      file: ./frontend/docker-services.dev.yml
      service: post-battle-frontend
    networks:
      - public
    depends_on:
      - post-battle-api
networks:
  public:
  private: