version: "3.9"

services:
  post-battle-api:
    build: .
    restart: unless-stopped
    entrypoint: "uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 3600"
    volumes:
      - ./src/:/post-battle-api/src/
    ports:
      - "3600:3600"